IMAGE_NAME = "ubuntu/xenial64"
N = 3

Vagrant.configure("2") do |config|
    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "ansible/cri-containerd.yaml"
    end
    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "172.42.42.10"
        master.vm.hostname = "k8s-master"
        config.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--hwvirtex", "on"]
            v.customize ["modifyvm", :id, "--vtxvpid", "on"]
            # bellow line is not supported with older versions of virtualbox
            # v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
            v.customize ["modifyvm", :id, "--largepages", "on"]
            v.customize ["modifyvm", :id, "--vtxux", "on"]
            v.memory = 2048
            v.cpus = 2
        end
        # master.vm.provision "shell", path: "bootstrap_master.sh"
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "172.42.42.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            config.vm.provider "virtualbox" do |v|
                v.customize ["modifyvm", :id, "--hwvirtex", "on"]
                v.customize ["modifyvm", :id, "--vtxvpid", "on"]
                # bellow line is not supported with older versions of virtualbox
                # v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
                v.customize ["modifyvm", :id, "--largepages", "on"]
                v.customize ["modifyvm", :id, "--vtxux", "on"]
                v.memory = 4096
                v.cpus = 2
            end
            # node.vm.provision "shell", path: "bootstrap_worker.sh"
        end
    end
end
