---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user
  namespace: ns

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ns-full-access
  namespace: ns
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - pods
  - deploy
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mcmp-scotturbina
  namespace: ns
subjects:
- kind: ServiceAccount
  name: user
  namespace: ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ns-full-access
